---
version: '3.6'

x-blockscout-ref:
  &blockscout-def
  image: consensys/blockscout:v4.0.0-beta
  container_name: blockscout
  restart: "no"
  environment:
    - PORT=4000
    - DATABASE_URL=ecto://postgres:postgres@blockscoutpostgres/postgres?ssl=false
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - NETWORK=quickstart
    - NETWORK=Dev Quickstart
    - SUBNETWORK=Quorum
    - CHAIN_ID=888
    - COIN=KAIBA
    - ETHEREUM_JSONRPC_VARIANT=geth
    - ETHEREUM_JSONRPC_TRANSPORT=http
    - ETHEREUM_JSONRPC_HTTP_URL=http://local.machine:8545
    - ETHEREUM_JSONRPC_TRACE_URL=http://local.machine:8545
    - ETHEREUM_JSONRPC_WS_URL=ws://local.machine:8546
  entrypoint:
    - /bin/sh
    - -c
    - |
      cd /opt/app/;
      echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
  depends_on:
    - blockscoutpostgres
  links:
    - blockscoutpostgres
  ports:
    - 26000:4000

x-blockscoutpostgres-ref:
  &blockscoutpostgres-def
  image: postgres:13.4-alpine
  restart: "on-failure"
  container_name: blockscoutpostgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  volumes:
    - blockscoutpostgres:/var/lib/postgresql/data
  ports:
    - 5432
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 5s
    timeout: 10s
    retries: 5

  
services:

  blockscout:
    << : *blockscout-def
    networks:
      quorum-dev-quickstart:
         ipv4_address: 172.16.239.51
    extra_hosts:
      - 'local.machine:172.17.1.1'
         
  blockscoutpostgres:
    << : *blockscoutpostgres-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.52
    extra_hosts:
      - 'local.machine:172.17.1.1'

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  blockscoutpostgres:
